apiVersion: v2
name: HomeBridge
version: 0.1.0
description: 'A Helm Chart for HomeBridge'
dependencies:
  - name: homebridge
    version: 0.5.0
    repository: https://homeenterpriseinc.github.io/helm-charts/
